steps:

  - name: node:lts
    entrypoint: bash
    args: [-c, "npm install -g pnpm && pnpm install && pnpm run build-storybook"]

  # Deploy the static files to the Cloud Storage bucket
  - name: gcr.io/cloud-builders/gsutil
    args: [rsync, -r, storybook-static, "gs://nuxt-ui-storybook"]

  # Set cache control for index.html to prevent caching issues
  - name: gcr.io/cloud-builders/gsutil
    args: [setmeta, -h, "Cache-Control:no-cache,max-age=0", "gs://nuxt-ui-storybook/index.html"]

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
