import type { UIConfig } from "@/types/ui";

const pinnedColumns = [
	"[&_[data-pinned=left]]:sticky",
	"[&_[data-pinned=left]]:bg-default",
	"[&_th[data-pinned=left]]:overflow-visible",
	"[&_td[data-pinned=left]]:overflow-visible",
	"[&_th[data-pinned=left]::after]:content-['']",
	"[&_td[data-pinned=left]::after]:content-['']",
	"[&_th[data-pinned=left]::after]:absolute",
	"[&_td[data-pinned=left]::after]:absolute",
	"[&_th[data-pinned=left]::after]:inset-y-0",
	"[&_td[data-pinned=left]::after]:inset-y-0",
	"[&_th[data-pinned=left]::after]:right-0",
	"[&_td[data-pinned=left]::after]:right-0",
	"[&_th[data-pinned=left]::after]:w-2.5",
	"[&_td[data-pinned=left]::after]:w-2.5",
	"[&_th[data-pinned=left]::after]:translate-x-full",
	"[&_td[data-pinned=left]::after]:translate-x-full",
	"[&_th[data-pinned=left]::after]:pointer-events-none",
	"[&_td[data-pinned=left]::after]:pointer-events-none",
	"[&_th[data-pinned=left]::after]:bg-gradient-to-r",
	"[&_td[data-pinned=left]::after]:bg-gradient-to-r",
	"[&_th[data-pinned=left]::after]:from-primary-900/15",
	"[&_td[data-pinned=left]::after]:from-primary-900/15",
	"[&_th[data-pinned=left]::after]:to-transparent",
	"[&_td[data-pinned=left]::after]:to-transparent",
	"[&_th[data-pinned=left]::after]:opacity-0",
	"[&_td[data-pinned=left]::after]:opacity-0",
	"[&_th[data-pinned=left]::after]:transition-opacity",
	"[&_td[data-pinned=left]::after]:transition-opacity",
	"[&_th[data-pinned=left]::after]:duration-300",
	"[&_td[data-pinned=left]::after]:duration-300",
	"[&_[data-pinned=right]]:sticky",
	"[&_[data-pinned=right]]:bg-default",
	"[&_th[data-pinned=right]]:overflow-visible",
	"[&_td[data-pinned=right]]:overflow-visible",
	"[&_th[data-pinned=right]::before]:content-['']",
	"[&_td[data-pinned=right]::before]:content-['']",
	"[&_th[data-pinned=right]::before]:absolute",
	"[&_td[data-pinned=right]::before]:absolute",
	"[&_th[data-pinned=right]::before]:inset-y-0",
	"[&_td[data-pinned=right]::before]:inset-y-0",
	"[&_th[data-pinned=right]::before]:left-0",
	"[&_td[data-pinned=right]::before]:left-0",
	"[&_th[data-pinned=right]::before]:w-2.5",
	"[&_td[data-pinned=right]::before]:w-2.5",
	"[&_th[data-pinned=right]::before]:-translate-x-full",
	"[&_td[data-pinned=right]::before]:-translate-x-full",
	"[&_th[data-pinned=right]::before]:pointer-events-none",
	"[&_td[data-pinned=right]::before]:pointer-events-none",
	"[&_th[data-pinned=right]::before]:bg-gradient-to-l",
	"[&_td[data-pinned=right]::before]:bg-gradient-to-l",
	"[&_th[data-pinned=right]::before]:from-primary-900/15",
	"[&_td[data-pinned=right]::before]:from-primary-900/15",
	"[&_th[data-pinned=right]::before]:to-transparent",
	"[&_td[data-pinned=right]::before]:to-transparent",
	"[&_th[data-pinned=right]::before]:opacity-0",
	"[&_td[data-pinned=right]::before]:opacity-0",
	"[&_th[data-pinned=right]::before]:transition-opacity",
	"[&_td[data-pinned=right]::before]:transition-opacity",
	"[&_th[data-pinned=right]::before]:duration-300",
	"[&_td[data-pinned=right]::before]:duration-300",
	"[&_th[data-pinned]]:z-2",
	"[&_td[data-pinned]]:z-1",
	"[&.is-scrolled-left]:overflow-visible!",
	"[&.is-scrolled-right]:overflow-visible!",
	"[&.is-scrolled-left_table]:overflow-visible!",
	"[&.is-scrolled-right_table]:overflow-visible!",
	"[&.is-scrolled-left_th[data-pinned=left]]:z-2",
	"[&.is-scrolled-left_td[data-pinned=left]]:z-2",
	"[&.is-scrolled-left_th[data-pinned=left]]:overflow-visible",
	"[&.is-scrolled-left_td[data-pinned=left]]:overflow-visible",
	"[&.is-scrolled-left_th[data-pinned=left]::after]:opacity-100",
	"[&.is-scrolled-left_td[data-pinned=left]::after]:opacity-100",
	"[&.is-scrolled-right_th[data-pinned=right]]:z-2",
	"[&.is-scrolled-right_td[data-pinned=right]]:z-2",
	"[&.is-scrolled-right_th[data-pinned=right]]:overflow-visible",
	"[&.is-scrolled-right_td[data-pinned=right]]:overflow-visible",
	"[&.is-scrolled-right_th[data-pinned=right]::before]:opacity-100",
	"[&.is-scrolled-right_td[data-pinned=right]::before]:opacity-100"
].join(" ");

export default {
	slots: {
		base: pinnedColumns,
		td: "text-primary-900"
	}
} satisfies UIConfig["table"];
