// Generates app/assets/css/variables.css from app/config/palette.ts.
// Run with `pnpm generate:colors`. The CSS is a build artifact — edit palette.ts instead.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gradients, palette, SHADES } from "../app/config/palette";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "../app/assets/css/variables.css");

// Everything is emitted under a single :root block (not @theme): Tailwind v4 tree-shakes
// unused @theme variables, which breaks colors referenced only at runtime (Nuxt UI semantic
// colors, bg-(--color-*) arbitrary values). Plain :root vars are always emitted.
const lines: string[] = [];

for (const [name, scale] of Object.entries(palette)) {
	for (const shade of SHADES) {
		lines.push(`\t--color-${name}-${shade}: ${scale[shade]};`);
	}
	lines.push("");
}

for (const [name, value] of Object.entries(gradients)) {
	lines.push(`\t--color-${name}: ${value};`);
}

const css = `/* AUTO-GENERATED by \`pnpm generate:colors\` from app/config/palette.ts. Do not edit by hand. */

:root {
${lines.join("\n")}
}
`;

writeFileSync(outPath, css);

console.log(`Generated ${outPath}`);
