// Generates app/assets/css/fallbacks.css — metric-adjusted local fallback faces for Saans.
// Run with `pnpm generate:fonts`. The CSS is a build artifact — re-run only when the font
// files or the FALLBACKS list change.
//
// Why not @nuxt/fonts: it skips fonts declared with a manual @font-face, and its fontaine
// integration cannot read metrics from local font files. The faces follow the same naming
// scheme @nuxt/fonts uses ("<family> Fallback: <font>") and are referenced by name in the
// --font-sans stack in main.css, with the generic families last as the terminal safety net.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { generateFontFace, getMetricsForFamily, readMetrics } from "fontaine";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "../app/assets/css/fallbacks.css");

const FALLBACKS = ["BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "Noto Sans"];

const VARIANTS = [
	{ file: "../app/assets/fonts/SaansVF.woff2", style: "normal" },
	{ file: "../app/assets/fonts/SaansVFItalics.woff2", style: "italic" }
];

const faces: string[] = [];

for (const variant of VARIANTS) {
	const metrics = await readMetrics(pathToFileURL(join(here, variant.file)).href);
	if (!metrics) throw new Error(`Cannot read metrics from ${variant.file}`);
	for (const fallback of FALLBACKS) {
		const fallbackMetrics = await getMetricsForFamily(fallback);
		if (!fallbackMetrics) throw new Error(`No metrics available for fallback font ${fallback}`);
		faces.push(generateFontFace(metrics, {
			"name": `Saans Fallback: ${fallback}`,
			"font": fallback,
			"metrics": fallbackMetrics,
			"font-weight": "100 900",
			"font-style": variant.style
		}));
	}
}

const css = `/* AUTO-GENERATED by \`pnpm generate:fonts\`. Do not edit by hand. */
${faces.join("")}`;

writeFileSync(outPath, css);

console.log(`Generated ${outPath}`);
